# Don't worry about getting the sources into the image; we'll do that
# at runtime:
deps_only: true
# Keep the .git directory in the work clone
keep_git: true

names:
  test: richfitz/mortality_bci

modules:
  - rrqueue
  - remake
  - rstan

r_packages:
  - dplyr
  - RCurl
  - downloader
  - rmarkdown
r_local_packages:
  - ../rrqueue
