# Don't worry about getting the sources into the image; we'll do that
# at runtime:
deps_only: true
# Keep the .git directory in the work clone
keep_git: true
# Use non broken versions of apt sources
apt_unstable: true

apt_packages:
  - gfortran

names:
  test: traitecoevo/mortality_bci

modules:
  - remake
  - rrqueue

r_packages:
  - rstan

r_github_packages:
  - traitecoevo/rrqueue
