# Manually list these so that we can install them with the main batch
# of packages.
r_packages:
  - RcppEigen
  - inline

commands:
  rstan:
    # neither on cran nor github and a pain to install
    command: |
      RUN MAKEVARS="-j1" install2.r --error
        --repos=http://cran.rstudio.com
        --repos=http://rstan.org/repo
        rstan
    after: r_packages
  upgrade_install2.r:
    # allow multiple repos in the rstan installation instructions:
    command: |
      RUN rm /usr/local/bin/install2.r &&
        wget --no-check-certificate
        https://raw.githubusercontent.com/cboettig/littler/master/examples/install2.r
        -O /usr/local/bin/install2.r
        && chmod +x /usr/local/bin/install2.r
    after: apt_packages
